#!/bin/sh

### en
DIALOG_RESULT=$(echo -e 'Exit I3\nBlock\nUnBlock\nSleep\nRbeoot\nPoverOFF\nEXIT' | rofi -dmenu -i -p "SYSTEM" -hide-scrollbar -tokenize -lines 7 -eh 1 -width 25 -location 0 -xoffset 0 -yoffset 0 -padding 20 -disable-history)

echo "This result is : $DIALOG_RESULT"
sleep 1;

if [ "$DIALOG_RESULT" = "Exit I3" ];
then
    i3-msg 'exit'
elif [ "$DIALOG_RESULT" = "Block" ];
then
    exec $HOME/.bin/multilock.sh -l blur
elif [ "$DIALOG_RESULT" = "UnBlock" ];
then
    exec $HOME/.bin/multilock.sh -s blur &
    exec systemctl suspend
elif [ "$DIALOG_RESULT" = "Sleep" ];
then
    exec systemctl hibernate
elif [ "$DIALOG_RESULT" = "Rbeoot" ];
then
    exec systemctl reboot
elif [ "$DIALOG_RESULT" = "PoverOFF" ];
then
    exec systemctl poweroff
elif [ "$DIALOG_RESULT" = "EXIT" ];
then
    exit 0
fi
